export const services = [
  {
    id: "electrician",
    name: "Electrician",
    description: "Wiring, appliance fixing, and emergency electrical support.",
    image:
      "https://images.unsplash.com/photo-1621905251189-08b45d6a269e?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "plumber",
    name: "Plumber",
    description: "Leak repair, bathroom fittings, and pipeline maintenance.",
    image:
      "https://images.unsplash.com/photo-1607472586893-edb57bdc0e39?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "cleaning",
    name: "Cleaning",
    description: "Home deep-cleaning and regular maintenance services.",
    image:
      "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "ac-repair",
    name: "AC Repair",
    description: "AC installation, gas refill, servicing, and cooling repair.",
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSnVafEZ_Doc36qdt9lTBO2F1eXxsnQCWq8oQ&s",
  },
  {
    id: "carpenter",
    name: "Carpenter",
    description: "Furniture repair, custom shelves, and woodwork tasks.",
    image:
      "https://images.unsplash.com/photo-1530124566582-a618bc2615dc?auto=format&fit=crop&w=900&q=80",
  },
  {
    id: "house-painting",
    name: "House Painting",
    description: "Interior and exterior painting, surface preparation, and finishing.",
    image:
      "https://images.unsplash.com/photo-1623413243687-6dfb79d7c3d6?auto=format&fit=crop&w=900&q=80",
  },
];

export const providers = [
  {
    id: "p1",
    name: "Rahul Lenka",
    serviceId: "electrician",
    serviceType: "Electrician",
    location: "Khandagiri",
    rating: 4.8,
    price: "₹499 / visit",
    reviews: ["Very professional and on-time.", "Solved issue in one visit."],
  },
  {
    id: "p2",
    name: "Sourav Das",
    serviceId: "electrician",
    serviceType: "Electrician",
    location: "Patia",
    rating: 4.6,
    price: "₹450 / visit",
    reviews: ["Good wiring checks.", "Quick and neat work."],
  },
  {
    id: "p3",
    name: "Akash Pradhan",
    serviceId: "electrician",
    serviceType: "Electrician",
    location: "Nayapalli",
    rating: 4.7,
    price: "₹520 / visit",
    reviews: ["Fixed MCB issue fast.", "Polite and skilled technician."],
  },
  {
    id: "p4",
    name: "Deepak Sahu",
    serviceId: "electrician",
    serviceType: "Electrician",
    location: "Saheed Nagar",
    rating: 4.5,
    price: "₹399 / visit",
    reviews: ["Affordable and reliable.", "Good same-day availability."],
  },
  {
    id: "p5",
    name: "Nikhil Behera",
    serviceId: "plumber",
    serviceType: "Plumber",
    location: "Old Town",
    rating: 4.5,
    price: "₹299 / visit",
    reviews: ["Quick response for leakage.", "Affordable and skilled."],
  },
  {
    id: "p6",
    name: "Rajeev Kumar",
    serviceId: "plumber",
    serviceType: "Plumber",
    location: "Jayadev Bihar",
    rating: 4.8,
    price: "₹380 / visit",
    reviews: ["Excellent bathroom fitting.", "Very professional visit."],
  },
  {
    id: "p7",
    name: "Manoj Singh",
    serviceId: "plumber",
    serviceType: "Plumber",
    location: "Ghatikia",
    rating: 4.6,
    price: "₹430 / visit",
    reviews: ["Fixed kitchen leakage quickly.", "Good service quality."],
  },
  {
    id: "p8",
    name: "Imran Ali",
    serviceId: "plumber",
    serviceType: "Plumber",
    location: "Nayapalli",
    rating: 4.4,
    price: "₹350 / visit",
    reviews: ["Budget-friendly option.", "Reached on time."],
  },
  {
    id: "p9",
    name: "Suhani Jena",
    serviceId: "cleaning",
    serviceType: "Cleaning",
    location: "Khandagiri",
    rating: 4.7,
    price: "₹399 / session",
    reviews: ["Detailed deep cleaning.", "Friendly and efficient."],
  },
  {
    id: "p10",
    name: "Priya Parida",
    serviceId: "cleaning",
    serviceType: "Cleaning",
    location: "Kalinga Nagar",
    rating: 4.8,
    price: "₹249 / session",
    reviews: ["Excellent deep cleaning.", "Very organized work."],
  },
  {
    id: "p11",
    name: "Manoj Rout",
    serviceId: "cleaning",
    serviceType: "Cleaning",
    location: "Pune",
    rating: 4.5,
    price: "₹300 / session",
    reviews: ["Good for regular cleaning.", "Quick and clean process."],
  },
  {
    id: "p12",
    name: "Sonia Hota",
    serviceId: "cleaning",
    serviceType: "Cleaning",
    location: "Kalinga Nagar",
    rating: 4.6,
    price: "₹380 / session",
    reviews: ["Great kitchen cleaning.", "Attention to detail is good."],
  },
  {
    id: "p13",
    name: "Ritesh Nayak",
    serviceId: "ac-repair",
    serviceType: "AC Repair",
    location: "Bhubaneswar",
    rating: 4.9,
    price: "₹599 / visit",
    reviews: ["AC cooling restored quickly.", "Professional servicing and cleanup."],
  },
  {
    id: "p14",
    name: "Vikash Nayak",
    serviceId: "ac-repair",
    serviceType: "AC Repair",
    location: "Cuttack",
    rating: 4.7,
    price: "₹550 / visit",
    reviews: ["Good gas refill service.", "Diagnosed issue correctly."],
  },
  {
    id: "p15",
    name: "Amit Behera",
    serviceId: "ac-repair",
    serviceType: "AC Repair",
    location: "Saheed Nagar",
    rating: 4.6,
    price: "₹530 / visit",
    reviews: ["Fast response in summer.", "Indoor unit cleaned well."],
  },
  {
    id: "p16",
    name: "Sanjay Mishra",
    serviceId: "ac-repair",
    serviceType: "AC Repair",
    location: "Patia",
    rating: 4.5,
    price: "₹500 / visit",
    reviews: ["Reasonable pricing.", "Professional installation support."],
  },
  {
    id: "p17",
    name: "Kunal Mohanty",
    serviceId: "carpenter",
    serviceType: "Carpenter",
    location: "Bhubaneswar",
    rating: 4.8,
    price: "₹650 / visit",
    reviews: ["Strong finishing quality.", "Great wardrobe repair."],
  },
  {
    id: "p18",
    name: "Rohit Das",
    serviceId: "carpenter",
    serviceType: "Carpenter",
    location: "Cuttack",
    rating: 4.6,
    price: "₹590 / visit",
    reviews: ["Fixed dining table neatly.", "Good behavior and punctual."],
  },
  {
    id: "p19",
    name: "Abhishek Jena",
    serviceId: "carpenter",
    serviceType: "Carpenter",
    location: "Patia",
    rating: 4.7,
    price: "₹700 / visit",
    reviews: ["Excellent shelf installation.", "Clean final finish."],
  },
  {
    id: "p20",
    name: "Hari Prasad",
    serviceId: "carpenter",
    serviceType: "Carpenter",
    location: "Ghatikia",
    rating: 4.5,
    price: "₹560 / visit",
    reviews: ["Quick repair work.", "Affordable and skilled carpenter."],
  },
];

export const initialUsers = [
  {
    id: "u1",
    name: "Neha Consumer",
    email: "consumer@demo.com",
    password: "123456",
    role: "consumer",
    approvalStatus: "approved",
    accountStatus: "active",
  },
  {
    id: "u2",
    name: "Arjun Provider",
    email: "provider@demo.com",
    password: "123456",
    role: "provider",
    approvalStatus: "approved",
    accountStatus: "active",
    location: "Patia",
  },
];

export const bookings = [
  { id: "b1", service: "Electrician", provider: "Rahul Sharma", status: "Pending", date: "06 May 2026" },
  { id: "b2", service: "Cleaning", provider: "Anjali Verma", status: "Accepted", date: "03 May 2026" },
  { id: "b3", service: "Plumber", provider: "Nikhil Mehta", status: "Completed", date: "29 Apr 2026" },
];

export const serviceRequests = [
  { id: "r1", customer: "Karan", service: "Wiring Repair", location: "Pune", status: "New" },
  { id: "r2", customer: "Mina", service: "Bathroom Leakage", location: "Delhi", status: "New" },
];
